version: '3.1'

services:
  backend:
    image: backend
    ports:
      - "3000:3000"
    links:
      - db:database
    environment:
      DB_HOST: database
    build:
      context: backend
      dockerfile: Dockerfile
  frontend:
    image: frontend
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    build:
      context: frontend
      dockerfile: Dockerfile
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: test
    volumes:
      - /var/wikipedia-project-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"