version: '3.1'

services:
  backend:
    image: backend
    ports:
      - "3333:3333"
    links:
      - db:database
    environment:
      DB_HOST: database
    build:
      context: backend
      dockerfile: Dockerfile
  frontend:
    image: frontend
    ports:
      - "80:8080"
    links:
      - backend:backend
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    build:
      context: frontend
      dockerfile: Dockerfile
  db:
    image: postgres
    environment:
      POSTGRES_DB: dawid
      POSTGRES_USER: dawid
      POSTGRES_PASSWORD: "&H2FEZ5+0X!y\"G8?!beWlV:j5"
    volumes:
      - /var/wikipedia-project-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"